# Generated by Django 5.1.3 on 2024-11-30 00:35

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField

def create_extensions(apps, schema_editor):
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION array_to_vector(input_array float[])
        RETURNS vector
        AS $$
        SELECT input_array::vector;
        $$ LANGUAGE SQL IMMUTABLE;
    """)

def reverse_extensions(apps, schema_editor):
    schema_editor.execute("DROP EXTENSION IF EXISTS vector CASCADE;")

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_extensions, reverse_extensions),
        migrations.CreateModel(
            name='TextEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', ArrayField(base_field=models.FloatField(), size=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='embeddings_created_idx')],
            },
        ),
    ]
