# Generated by Django 5.1.3 on 2024-11-30 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_paragraphs', models.IntegerField(default=0)),
                ('processed_paragraphs', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameIndex(
            model_name='textembedding',
            new_name='embeddings__created_9a8086_idx',
            old_name='embeddings_created_idx',
        ),
        migrations.AddField(
            model_name='textembedding',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='embeddings.document'),
            preserve_default=False,
        ),
    ]
