# Generated by Django 5.1.4 on 2024-12-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0003_create_vector_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textembedding',
            options={'ordering': ['chunk_index']},
        ),
        migrations.AddField(
            model_name='textembedding',
            name='chunk_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
