# Generated by Django 5.1.3 on 2024-11-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0003_collection_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='embeddings.collection'),
        ),
    ]
