# Generated by Django 5.1.3 on 2024-12-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0004_alter_document_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='collection',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
